### ISSUE TITLE
Create dinner recipe

### ISSUE THREAD

**Issue by dbatomunkueva** [IntroToCode/CodeMates6_Spring23#1]
## 💬 Discussion topic

Coming up with the recipe for quick and easy lunch

## ❗ Potential issues

N/A

## 👥 People to consult

N/A

## 📃 Details

We'll work on CRUNCHY SOUTHWESTERN CHICKEN WRAP from [this website](https://dinnersdishesanddesserts.com/crunchy-southwestern-chicken-wrap/) 

Servings - Chioma
Time to prepare - Dara
Ingredients - Katherine
Equipment needed - Giovanni
Steps for preparation - Maelym

**Comment by katherinezepeda** [comment]
The work plan and delegation of tasks look good to me.

**Comment by katherinezepeda** [comment]
@ChiomaEkedede @dbatomunkueva @berkeleygio have any of you heard from Maelyn?

**Comment by ChiomaEkedede** [comment]
No I have not, but i think she has been assigned a task, and tagged in the other issue thread

**Comment by katherinezepeda** [comment]
When I try to search for her tag, I get nothing showing up. Do you see her profile?

**Comment by MaelymMedina** [comment]
@ChiomaEkedede @dbatomunkueva @katherinezepeda @berkeleygio I have made the last changes to my section. Can you please confirm and merge?

**Comment by MaelymMedina** [comment]
I will close this issue since we are done with the recipe
