### ISSUE TITLE
BREAKFAST

### ISSUE THREAD

**Issue by ChiomaEkedede** [IntroToCode/CodeMates6_Spring23#2]
## 💬 Discussion topic

Good old fashion pancake recipe! This will be delicious! 😋 
## ❗ Potential issues
Will need to figure out serving sizes, prep time can vary, equipment may not be easy to find

## 👥 People to consult
1. Servings - @ChiomaEkedede 
2. time to prep - @dbatomunkueva 
3. ingredients - @katherinezepeda 
4. equipment - @berkeleygio 
5. steps for prep - maelym

@joewadcan @aparnachaganty 
## 📃 Details
We will be following this recipe. Please submit a pull request for each step in the recipe. We will have two people review each pull request. Please tag two people when you submit your pull request for review. The last person to review will merge pull request (if it looks good).
https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/

**Comment by katherinezepeda** [comment]
Hey @ChiomaEkedede , great idea to focus on old-fashioned-pancakes! Might we consider adding some fruit on top?

**Comment by ChiomaEkedede** [comment]
@katherinezepeda @berkeleygio Dara and I have made our updates. Please review and add yours as well. Then we can go ahead and commit

**Comment by ChiomaEkedede** [comment]
> 

I would prefer to keep it simple for this launch 🚀

**Comment by katherinezepeda** [comment]
@ChiomaEkedede Agreed, let's keep it simple and revisit after the initial launch.

**Comment by katherinezepeda** [comment]
@ChiomaEkedede @dbatomunkueva @berkeleygio, I've reviewed the pull requests where I was tagged and submitted my proposed changes for the list of ingredients. Let me know if you have any questions.

**Comment by berkeleygio** [comment]
@ChiomaEkedede @dbatomunkueva @katherinezepeda @maelym I will be updating the equipment section tonight and making a pull request--please be on the lookout for that.

**Comment by MaelymMedina** [comment]
@ChiomaEkedede @dbatomunkueva @katherinezepeda @berkeleygio I have made the last changes to my section. Can you please confirm and merge?

**Comment by MaelymMedina** [comment]
I will close this issue since we are done with the recipe
